### PR TITLE
Do optimizations and refactoring using coding principles as requested in my previous pull request 

### PR DESCRIPTION
**Pull request by outmaneuver**
Refactor and optimize various modules in the `discmoji` project.

* **discmoji/_http.py**
  - Reuse `aiohttp.ClientSession` instead of creating a new one for each request.
  - Refactor `ratelimited` method to avoid unnecessary async calls.
  - Optimize `_send` method to handle JSON decoding more efficiently.

* **discmoji/bot.py**
  - Refactor `connect` method to avoid creating a new event loop and instead use the existing one.
  - Optimize `GuildManager` class to avoid synchronous calls to `asyncio.run`.

* **discmoji/channel.py**
  - Optimize `GuildTextChannel` class by avoiding synchronous calls to `asyncio.run`.
  - Refactor constructor to handle asynchronous requests more efficiently.

* **discmoji/cli/_cli.py**
  - Refactor `__CLI__` class to improve readability and maintainability.
  - Optimize `is_cmd_invoked` method to handle command invocation more efficiently.

* **discmoji/command.py**
  - Optimize `Command` class by handling errors asynchronously.
  - Refactor `__call__` method to improve error handling.

* **discmoji/context.py**
  - Optimize `Invoked` class by avoiding synchronous calls to `asyncio.run`.
  - Refactor `_construct` method to handle asynchronous requests more efficiently.

### CODE REVIEW

**Comment by outmaneuver** [comment]
This pull request includes several changes to improve the asynchronous behavior and code readability of the `discmoji` library. The most important changes include converting synchronous code to asynchronous, refactoring methods for better readability, and updating type annotations.

### Asynchronous Improvements:
* [`discmoji/_http.py`](diffhunk://#diff-ae992b92d65b55ae606f7e81f5a69994a7c3962db78e0a5be09e3727ab7ef8c1L20-R33): Converted the `ratelimited` method from asynchronous to synchronous, simplifying its logic and ensuring proper type handling for the `Retry-After` header.
* [`discmoji/bot.py`](diffhunk://#diff-c474955ace9cdb380e8f0dab4fd647236781530e4cb302bed264a98be9c4a8ccL55-R56): Updated the `get_guild` method to use `await` for the `send_request` call, ensuring it operates asynchronously.
* [`discmoji/bot.py`](diffhunk://#diff-c474955ace9cdb380e8f0dab4fd647236781530e4cb302bed264a98be9c4a8ccL83-R89): Refactored the `connect` method to handle heartbeats and reconnections asynchronously, removing the need for a new event loop.
* [`discmoji/context.py`](diffhunk://#diff-12ed7a614974b1c816269d66aeb5869363024a8773320577ec4b72a035991250L29-R37): Converted the `_construct` method to be asynchronous, ensuring that all HTTP requests within it are awaited.
* [`discmoji/context.py`](diffhunk://#diff-12ed7a614974b1c816269d66aeb5869363024a8773320577ec4b72a035991250L53-R62): Updated the `invoked_cmd_handler` method to use `await` for `asyncio.sleep` and `_construct` calls.

### Code Readability and Type Annotations:
* [`discmoji/channel.py`](diffhunk://#diff-02f73fb47d794ce0f1e996902154e877443d47214bfbc515ca70982d2d954c52L4-R11): Removed `asyncio.run` from the `GuildTextChannel` constructor and added an `initialize` method to handle asynchronous initialization. [[1]](diffhunk://#diff-02f73fb47d794ce0f1e996902154e877443d47214bfbc515ca70982d2d954c52L4-R11) [[2]](diffhunk://#diff-02f73fb47d794ce0f1e996902154e877443d47214bfbc515ca70982d2d954c52R22-R27)
* [`discmoji/cli/_cli.py`](diffhunk://#diff-17dffd863d56cc484a4e4a6cac13fa9a765fbd71444ebbbba6213c4bf7521085L2-R19): Renamed the `__CLI__` class to `CLI`, and updated type annotations and method names for better readability.
* [`discmoji/command.py`](diffhunk://#diff-b2d3320aed50bb95fdd18ff8a3856fbc65db964b34bc74ba946f02f012ddb068L15-R30): Made the `__call__` method asynchronous and updated error handling to be more robust.

**Comment by mojidev-py** [comment]
Ok, i'll merge this into the optimization branch, but i'm going to request a review first

**Review by XenonPy — APPROVED** [review]
I see the principles behind the changes here, I think that these could be pushed to the previous `optimization` branch created by @mojidev-py... 

I'm casting my vote of approval.

**Comment by XenonPy** [comment]
Since I see @mojidev-py based his decision on the review, I'm going to merge this...

**Pull request merged**
